[package]
name = "evallocator"
version = "0.1.0"
authors = ["Raphael Bost <raphael_bost@alumni.brown.edu>"]
edition = "2018"

[dependencies]
rand = "^0.7.0"
indicatif = "0.11.0"
rayon = "^1.1.0"
gnuplot = "^0.0.31"